### ISSUE TITLE
on team creation: java.sql.SQLSyntaxErrorException: Table 'ipat.hibernate_sequence' doesn't exist  

### ISSUE THREAD

**Issue by mschaaf** [Dica-Developer/weplantaforest#205]
```
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2019-12-03 20:31:26.551 ERROR 13545 --- [nio-8081-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table 'ipat.hibernate_sequence' doesn't exist
2019-12-03 20:31:26.554 DEBUG 13545 --- [nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Failed to complete request: org.springframework.dao.InvalidDataAccessResourceUsageException: error performing isolated work; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: error performing
isolated work
2019-12-03 20:31:26.558 ERROR 13545 --- [nio-8081-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: error performin
g isolated work; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: error performing isolated work] with root cause

java.sql.SQLSyntaxErrorException: Table 'ipat.hibernate_sequence' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.18.jar:8.0.18]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.18.jar:8.0.18]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.18.jar:8.0.18]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.18.jar:8.0.18]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.18.jar:8.0.18]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.4.1.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.1.jar:na]
        at org.hibernate.id.enhanced.TableStructure.executeQuery(TableStructure.java:216) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
        at org.hibernate.id.enhanced.TableStructure.access$300(TableStructure.java:46) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
        at org.hibernate.id.enhanced.TableStructure$1$1.execute(TableStructure.java:138) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
        at org.hibernate.id.enhanced.TableStructure$1$1.execute(TableStructure.java:126) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
        at org.hibernate.jdbc.WorkExecutor.executeReturningWork(WorkExecutor.java:55) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
        at org.hibernate.jdbc.AbstractReturningWork.accept(AbstractReturningWork.java:34) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcIsolationDelegate.delegateWork(JdbcIsolationDelegate.java:57) ~[hibernate-core-5.4.8.Final.jar:5.4.8.Final]
        at org.hibernate.id.enhanced.Ta
```

**Comment by mschaaf** [comment]
@Gab0rB lets have a look together. I thought we already fixed this.

**Comment by mschaaf** [comment]
This is fixed now in all 3 modules, we fixed it before only for the article-manager.

**Comment by mschaaf** [comment]
Crap, this is not enough. Still something wrong.

**Comment by mschaaf** [comment]
Oh man, found now how to set it correctly and checked it localy `spring.jpa.properties.hibernate.id.new_generator_mappings=false`
