### ISSUE TITLE
pdf as image does not work

### ISSUE THREAD

**Issue by mschaaf** [Dica-Developer/weplantaforest#279]
```
2021-02-26 17:00:47.775 ERROR 1946 --- [nio-8081-exec-9] o.d.weplantaforest.user.UserController   : Error occured while trying to get image nunovo Immobilienwerte GmbH.pdf in folder: /home/ipat/iplantatree/ipat-data/ipat_uploads/images/user/nunovo Immobilienwerte GmbH.pdf

net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable ImageReader found for source data.
        at net.coobird.thumbnailator.tasks.io.InputStreamImageSource.read(Unknown Source) ~[thumbnailator-0.4.8.jar:0.4.8]
        at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source) ~[thumbnailator-0.4.8.jar:0.4.8]
        at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source) ~[thumbnailator-0.4.8.jar:0.4.8]
        at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source) ~[thumbnailator-0.4.8.jar:0.4.8]
        at org.dicadeveloper.weplantaforest.common.image.ImageHelper.writeImageToOutputStream(ImageHelper.java:40) ~[common.jar:na]
        at org.dicadeveloper.weplantaforest.user.UserController.getImage(UserController.java:65) ~[wpaf-user-0.0.1-SNAPSHOT.jar:na]
        at jdk.internal.reflect.GeneratedMethodAccessor196.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.jav
```

**Comment by mschaaf** [comment]
closed with https://github.com/Dica-Developer/weplantaforest/commit/41fd06e885f1fb798d735b87d950c60c4e1ddc44 and https://github.com/Dica-Developer/weplantaforest/commit/e9dd2fa71c95670b9ef443491d6f779bbcf8cb38
