### ISSUE TITLE
some receipts are not sent

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#332]
User Shaddy reports, that not all receipts are sent to him. 
"zum Beispiel hatte ich die Quittung vom 24.12. bekommen, aber nicht die vom 21.12." He says that he doesn´t use a spam filter.

**Comment by mschaaf** [comment]
@gerolsteinernaturell please check if the mails are sent via our provider.

**Comment by Gab0rB** [comment]
--Exception handling in MailHelper.java

com.sun.mail.smtp.SMTPSendFailedException: 432 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=DBAPR08MB5814.eurprd08.prod.outlook.com]

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2358) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:2110) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1316) ~[javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.Transport.send0(Transport.java:255) ~[javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.Transport.send(Transport.java:124) ~[javax.mail-1.6.2.jar:1.6.2]
	at org.dicadeveloper.weplantaforest.common.mail.MailHelper.sendAMessageWithAttachement(MailHelper.java:101) ~[common.jar:na]
	at org.dicadeveloper.weplantaforest.receipt.ReceiptService$1.run(ReceiptService.java:57) ~[wpaf-user-0.0.1-SNAPSHOT.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-05-12 10:32:59.913 ERROR 19199 --- [       Thread-6] o.d.w.common.mail.MailHelper             :     ** ValidUnsent Addresses

com.sun.mail.smtp.SMTPSendFailedException: 432 4.3.2 Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. [Hostname=DBAPR08MB5814.eurprd08.prod.outlook.com]

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2358) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:2110) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1316) ~[javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.Transport.send0(Transport.java:255) ~[javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.Transport.send(Transport.java:124) ~[javax.mail-1.6.2.jar:1.6.2]
	at org.dicadeveloper.weplantaforest.common.mail.MailHelper.sendAMessageWithAttachement(MailHelper.java:101) ~[common.jar:na]
	at org.dicadeveloper.weplantaforest.receipt.ReceiptService$1.run(ReceiptService.java:57) ~[wpaf-user-0.0.1-SNAPSHOT.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-05-12 10:32:59.915 ERROR 19199 --- [       Thread-6] o.d.w.common.mail.MailHelper             :          Drahret@aol.com
